"""
Pydantic models for LLM request and response structures.
Defines structured outputs for Gemini API responses.
"""

from pydantic import BaseModel, Field, field_validator
from typing import List, Optional


class QueryPlan(BaseModel):
    """
    A single query in a multi-query analysis plan.

    Generated by the LLM to answer part of the user's question.
    """

    query_id: str = Field(
        ...,
        description="Unique identifier for this query (e.g., 'q1', 'q2')"
    )

    purpose: str = Field(
        ...,
        min_length=5,
        max_length=200,
        description="Brief description of what this query answers (in Spanish)"
    )

    sql_query: str = Field(
        ...,
        min_length=10,
        description="SQL Server query to execute"
    )

    @field_validator('sql_query')
    @classmethod
    def validate_sql_query(cls, v: str) -> str:
        """Basic SQL query validation."""
        v = v.strip()
        if not v.upper().startswith('SELECT'):
            raise ValueError("SQL query must start with SELECT")
        return v


class LLMMultiQueryResponse(BaseModel):
    """
    Structured response from Gemini LLM for multi-query analysis.

    Contains a list of queries to execute to answer the user's question.
    """

    queries: List[QueryPlan] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="List of queries to execute (1-5 queries)"
    )

    @field_validator('queries')
    @classmethod
    def validate_query_count(cls, v: List[QueryPlan]) -> List[QueryPlan]:
        """Ensure we have 1-5 queries."""
        if len(v) < 1:
            raise ValueError("At least 1 query is required")
        if len(v) > 5:
            raise ValueError(f"Maximum 5 queries allowed, got {len(v)}")
        return v


class LLMPromptContext(BaseModel):
    """
    Context information for LLM prompts.
    """

    database_schema: str = Field(
        ...,
        description="Formatted database schema"
    )

    user_prompt: str = Field(
        ...,
        min_length=5,
        max_length=500,
        description="User's question in Spanish"
    )

    additional_context: Optional[str] = Field(
        None,
        description="Additional context or constraints"
    )


class LLMError(Exception):
    """Base exception for LLM-related errors."""
    pass


class LLMAPIError(LLMError):
    """Raised when Gemini API call fails."""
    pass


class LLMParseError(LLMError):
    """Raised when LLM response cannot be parsed."""
    pass


class LLMValidationError(LLMError):
    """Raised when LLM response fails validation."""
    pass
